### ISSUE TITLE
Invalid RMC messages exception

### ISSUE THREAD

**Issue by coolacid** [stevemarple/MicroNMEA#1]
When trying to use this library on a ESP board, the following GPS message causes a Fatal Exception: 

`$GPRMC,194812.00,V,,,,,,,290317,,,N*74`

Currently, as a work around, I check if _isValid is false and return false which seems to work, but either I haven't gotten a bad message or it's not optimal

Great module, thanks!

**Comment by stevemarple** [comment]
The intention was that all fields present would be parsed and made available to the end user, even if the fix is invalid; this is useful for cases when the GPS includes a battery-backed clock. I've ammended the parsing to handle missing latitude/longitude fields for GGA and RMC messages and added your example GPS message as a test case. 

Does this work for you now?
